# -*- coding: utf-8 -*-

# Form implementation generated from reading ui_detect file 'stats.ui_detect'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 468)
        self.textEdit = QtWidgets.QPlainTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(50, 30, 261, 371))
        self.textEdit.setObjectName("textEdit")
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(380, 160, 113, 32))
        self.button.setObjectName("button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "统计薪资"))
        self.textEdit.setPlaceholderText(_translate("Form", "请输入薪资表"))
        self.button.setText(_translate("Form", "统计"))
