# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.nowtime = QtWidgets.QLabel(self.centralwidget)
        self.nowtime.setText("")
        self.nowtime.setObjectName("nowtime")
        self.gridLayout.addWidget(self.nowtime, 2, 4, 1, 1)
        self.playlistBox = QtWidgets.QComboBox(self.centralwidget)
        self.playlistBox.setObjectName("playlistBox")
        self.playlistBox.addItem("")
        self.playlistBox.addItem("")
        self.playlistBox.addItem("")
        self.gridLayout.addWidget(self.playlistBox, 1, 4, 1, 1)
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setObjectName("play_button")
        self.gridLayout.addWidget(self.play_button, 3, 0, 1, 1)
        self.videoout = QVideoWidget(self.centralwidget)
        self.videoout.setEnabled(True)
        self.videoout.setObjectName("videoout")
        self.gridLayout.addWidget(self.videoout, 0, 0, 2, 4)
        self.mid_button = QtWidgets.QPushButton(self.centralwidget)
        self.mid_button.setObjectName("mid_button")
        self.gridLayout.addWidget(self.mid_button, 3, 2, 1, 1)
        self.timeSlider = QtWidgets.QSlider(self.centralwidget)
        self.timeSlider.setEnabled(True)
        self.timeSlider.setMaximum(99)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.gridLayout.addWidget(self.timeSlider, 2, 0, 1, 4)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setEnabled(True)
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout.addWidget(self.volumeSlider, 1, 5, 2, 2)
        self.volume = QtWidgets.QLabel(self.centralwidget)
        self.volume.setObjectName("volume")
        self.gridLayout.addWidget(self.volume, 3, 5, 1, 2)
        self.listvidename = QtWidgets.QListWidget(self.centralwidget)
        self.listvidename.setObjectName("listvidename")
        self.gridLayout.addWidget(self.listvidename, 0, 4, 1, 3)
        self.left_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_button.setEnabled(True)
        self.left_button.setObjectName("left_button")
        self.gridLayout.addWidget(self.left_button, 3, 1, 1, 1)
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setObjectName("right_button")
        self.gridLayout.addWidget(self.right_button, 3, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 5)
        self.gridLayout.setColumnStretch(3, 5)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 5)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionfiles = QtWidgets.QAction(MainWindow)
        self.actionfiles.setObjectName("actionfiles")
        self.actiondirs = QtWidgets.QAction(MainWindow)
        self.actiondirs.setObjectName("actiondirs")
        self.actionnext = QtWidgets.QAction(MainWindow)
        self.actionnext.setEnabled(True)
        self.actionnext.setObjectName("actionnext")
        self.actionprevious = QtWidgets.QAction(MainWindow)
        self.actionprevious.setObjectName("actionprevious")
        self.actionpause = QtWidgets.QAction(MainWindow)
        self.actionpause.setObjectName("actionpause")
        self.actionstop = QtWidgets.QAction(MainWindow)
        self.actionstop.setObjectName("actionstop")
        self.menu.addAction(self.actionfiles)
        self.menu.addAction(self.actiondirs)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionprevious)
        self.toolBar.addAction(self.actionpause)
        self.toolBar.addAction(self.actionnext)
        self.toolBar.addAction(self.actionstop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playlistBox.setItemText(0, _translate("MainWindow", "顺序播放"))
        self.playlistBox.setItemText(1, _translate("MainWindow", "随机播放"))
        self.playlistBox.setItemText(2, _translate("MainWindow", "洗脑循环"))
        self.play_button.setText(_translate("MainWindow", "播放"))
        self.mid_button.setText(_translate("MainWindow", "暂停"))
        self.volume.setText(_translate("MainWindow", "音量"))
        self.left_button.setText(_translate("MainWindow", "快退"))
        self.right_button.setText(_translate("MainWindow", "快进"))
        self.menu.setTitle(_translate("MainWindow", "打开文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionfiles.setText(_translate("MainWindow", "文件"))
        self.actiondirs.setText(_translate("MainWindow", "文件夹"))
        self.actionnext.setText(_translate("MainWindow", "下一部"))
        self.actionnext.setToolTip(_translate("MainWindow", "下首歌"))
        self.actionprevious.setText(_translate("MainWindow", "上一部"))
        self.actionprevious.setToolTip(_translate("MainWindow", "上"))
        self.actionpause.setText(_translate("MainWindow", "暂停"))
        # self.actionpause.setToolyiTip(_translate("MainWindow", "暂停"))
        self.actionpause.setToolTip(_translate("MainWindow", "暂停"))
        self.actionstop.setText(_translate("MainWindow", "停止"))
from PyQt5.QtMultimediaWidgets import QVideoWidget

